[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.build]
cmds = [
  "python3 -m pip install -r requirements.txt",
  "ls -la static/",
  "ls -la templates/"
]

[phases.start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"