[build]
builder = "nixpacks"
buildCommand = "chmod +x build.sh && ./build.sh"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_VERSION = "18"
PYTHON_VERSION = "3.11"